fails:The break statement in a block captured and delegated to another method repeatedly breaks out of the block
fails:The break statement in a captured block when the invocation of the scope creating the block is still active raises a LocalJumpError when invoking the block from the scope creating the block
fails:The break statement in a captured block when the invocation of the scope creating the block is still active raises a LocalJumpError when invoking the block from a method
fails:The break statement in a captured block when the invocation of the scope creating the block is still active raises a LocalJumpError when yielding to the block
fails:The break statement in a captured block from a scope that has returned raises a LocalJumpError when calling the block from a method
fails:The break statement in a captured block from a scope that has returned raises a LocalJumpError when yielding to the block
fails:The break statement in a captured block from another thread raises a LocalJumpError when getting the value from another thread
fails:Break inside a while loop causes a call with a block to return when run
fails:Executing break from within a block returns from the original invoking method even in case of chained calls
fails:Executing break from within a block runs ensures when continuing upward
fails:Executing break from within a block doesn't run ensures in the destination method
