fails:The next statement from within the block returns to the currently yielding method in case of chained calls
fails:The next statement from within the block skips following code outside an exception block
fails:The next statement in a loop causes nested ensure blocks to run
fails:The next statement in a loop causes ensure blocks to run when mixed with break
fails:The next statement in a loop when not passed an argument causes ensure blocks to run
fails:The next statement in a loop when not passed an argument causes ensure blocks to run when nested in an block
fails:The next statement in a loop when passed an argument causes ensure blocks to run
fails:The next statement in a loop when passed an argument causes ensure blocks to run when nested in an block
fails:Assignment via next assigns splatted objects
fails:Assignment via next assigns splatted objects to a splatted reference via a splatted yield
fails:Assignment via next assigns objects to multiple variables
fails:Assignment via next assigns splatted objects to multiple variables
